# Generated by Django 4.2.7 on 2023-11-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True, verbose_name='Название')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотрено')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватный')),
                ('is_record_statistic', models.BooleanField(blank=True, default=False, null=True, verbose_name='Записывать статистику')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип теста')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вопрос')),
                ('type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип вопроса')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor_app.testmodel')),
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor_app.typetestmodel', verbose_name='Тип теста'),
        ),
    ]
