# Generated by Django 4.2.7 on 2023-11-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0002_testanswermodel_alter_testquestionmodel_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поля')),
            ],
        ),
        migrations.AlterField(
            model_name='testquestionmodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor_app.typequestionmodel'),
        ),
    ]
