# Generated by Django 4.2.7 on 2023-11-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0003_typequestionmodel_alter_testquestionmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswermodel',
            name='answer_points',
            field=models.IntegerField(default=1, verbose_name='Баллы за ответ'),
        ),
        migrations.AddField(
            model_name='testquestionmodel',
            name='has_diff_point',
            field=models.BooleanField(default=False),
        ),
    ]
