# Generated by Django 4.2.7 on 2023-11-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0004_testanswermodel_answer_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='is_different',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Сообщения в зависимости от баллов'),
        ),
        migrations.CreateModel(
            name='MessageFinishedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Т')),
                ('points', models.IntegerField(default=0)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_finish_rel', to='editor_app.testmodel')),
            ],
        ),
    ]
