# Generated by Django 4.2.7 on 2023-11-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0005_testmodel_is_different_messagefinishedtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='is_different',
            new_name='is_different_msg',
        ),
    ]
